import type { Unit, ContentSection } from './types';

export const UNITS: Unit[] = [
  {
    id: 1,
    title: 'Resources and Development',
    icon: '🗺️',
    chapters: [
      { id: 1, title: 'Resources', active: true },
      { id: 2, title: 'Land, Soil and Water Resources', active: false },
      { id: 3, title: 'Natural Vegetation and Wildlife', active: false },
      { id: 4, title: 'Mineral and Energy Resources', active: false },
      { id: 5, title: 'Agriculture', active: false },
      { id: 6, title: 'Industry', active: false },
      { id: 7, title: 'Human Resource', active: false },
    ],
  },
  {
    id: 2,
    title: 'Modern Period',
    icon: '🏰',
    chapters: [
      { id: 1, title: 'Modern India', active: false },
      { id: 2, title: 'Colonisation of India', active: false },
      { id: 3, title: "The Company's Civil Administration and Revenue Policy", active: false },
      { id: 4, title: 'Tribal Resistance', active: false },
      { id: 5, title: 'The Revolt of 1857', active: false },
      { id: 6, title: 'Colonialism and Urban Change', active: false },
      { id: 7, title: 'Crafts and Industries', active: false },
      { id: 8, title: 'Education and British Rule', active: false },
      { id: 9, title: 'Women, Caste and Reform', active: false },
      { id: 10, title: 'Changes in Art and Architecture', active: false },
      { id: 11, title: 'Rise of Indian Nationalism', active: false },
      { id: 12, title: 'National Movement – Fulfilment', active: false },
      { id: 13, title: 'India after Independence', active: false },
    ],
  },
  {
    id: 3,
    title: 'Social and Political Life',
    icon: '⚖️',
    chapters: [
      { id: 1, title: 'The Indian Constitution', active: false },
      { id: 2, title: 'Understanding Secularism', active: false },
      { id: 3, title: 'Our Fundamental Rights and Duties', active: false },
      { id: 4, title: 'Parliamentary Government: The Union Legislature', active: false },
      { id: 5, title: 'Parliamentary Government: The Union Executive', active: false },
      { id: 6, title: 'The Judiciary', active: false },
      { id: 7, title: 'Role of Police and Courts', active: false },
      { id: 8, title: 'Marginalised Groups and Social Justice', active: false },
      { id: 9, title: 'Public Facilities and Social Justice', active: false },
      { id: 10, title: 'Laws and Public Welfare', active: false },
    ],
  },
];

export const CHAPTER_1_CONTENT: ContentSection[] = [
    {
        title: 'A. Oral Questions',
        questions: [
            { q: '1. Give two examples of resources that have economic value.', a: 'Gold and petroleum.' },
            { q: '2. What are the three main types of resources?', a: 'Natural resources, human resources, and man-made resources.' },
            { q: '3. What are natural resources? Give two examples.', a: 'Resources obtained from nature are called natural resources. Examples: Air and water.' },
            { q: '4. What are inexhaustible resources?', a: 'Resources that never get exhausted and are unlimited in supply, like sunlight and wind.' },
            { q: '5. Name a natural resource which can be generated by us.', a: 'Forests (by afforestation or tree planting).' },
            { q: '6. Give two examples of localised resources.', a: 'Coal and petroleum.' },
        ],
    },
    {
        title: 'B. Answer in not more than 20 words',
        questions: [
            { q: '1. Define resource.', a: 'Anything that has utility and value is called a resource.' },
            { q: '2. Classify natural resources on the basis of their nature. Give two examples of each.', a: '(i) Biotic – Plants, animals\n(ii) Abiotic – Water, minerals' },
            { q: '3. What is technology?', a: 'Technology is the use of skill and knowledge to make things easier and more useful.' },
            { q: '4. What is meant by recycling? Name a resource that can be recycled.', a: 'Using waste materials again after processing is recycling. Example: Iron.' },
            { q: '5. What is a reserve?', a: 'A reserve is a part of a resource that can be used in the future.' },
        ],
    },
    {
        title: 'C. Answer in not more than 40 words',
        questions: [
            { q: '1. Differentiate between human resource and man-made resource. Give suitable examples.', a: 'Human resources refer to people with skills and abilities (e.g., teachers, doctors). Man-made resources are created by humans using natural resources (e.g., buildings, machines).' },
            { q: '2. With the help of an example, distinguish between actual and potential resources.', a: 'Actual resources are being used at present, like petroleum in Saudi Arabia. Potential resources are known but not used yet, like solar energy in deserts.' },
            { q: '3. What do you understand by conservation of resources?', a: 'Conservation of resources means careful and wise use of resources to prevent their depletion and ensure their availability for the future.' },
        ],
    },
    {
        title: 'D. Answer in not more than 100 words',
        questions: [
            {
                q: '1. Distinguish between renewable and non-renewable resources. Give two examples of each. Discuss whether renewable resources can ever be exhausted.',
                isTable: true,
                table: {
                    headers: ['Type', 'Description', 'Examples'],
                    rows: [
                        ['Renewable', 'Resources that can be renewed naturally.', 'Water, forests'],
                        ['Non-renewable', 'Resources that cannot be replaced easily once used.', 'Coal, petroleum']
                    ]
                },
                a: 'Renewable resources can get exhausted if used carelessly, such as forests being cut faster than they grow.',
            },
            {
                q: '2. What is sustainable development? Why is it required? Mention any three ways in which resources can be used sustainably.',
                a: 'Sustainable development means using resources wisely so that future generations can also benefit. It is required to balance economic growth with environmental protection.\n\nThree ways:\n1. Recycling and reusing materials.\n2. Avoiding wastage of water and energy.\n3. Planting trees and protecting forests.',
            },
        ],
    },
    {
        title: 'E. Think and Answer',
        questions: [
            { q: '1. Why are human beings considered a resource?', a: 'Because they have knowledge, skills, and intelligence to use and develop other resources.' },
            { q: '2. Why are limited fuels and metal ores non-renewable resources?', a: 'Because they take millions of years to form and cannot be replaced once used.' },
            { q: '3. How can a potential resource become an actual resource?', a: 'When technology and demand make it possible to use it, a potential resource becomes actual.' },
        ],
    },
    {
        title: 'F. Fill in the Blanks',
        questions: [
            { q: '1. All resources have some utility and ____.', a: 'value' },
            { q: '2. Resources that give us pleasure have ____ value.', a: 'aesthetic' },
            { q: '3. Animals are a type of ____ resource.', a: 'biotic' },
            { q: '4. ____ resources can be generated by us.', a: 'Man-made' },
            { q: '5. Resources that have not yet been identified or cannot be used at present are called ____ resources.', a: 'potential' },
        ],
    },
    {
        title: 'G. True or False',
        questions: [
            { q: '1. A resource is useful only when its useful properties are recognised.', a: 'True' },
            { q: '2. Things that can be bought and sold are resources with economic value.', a: 'True' },
            { q: '3. Things that only give us pleasure are not resources.', a: 'False' },
            { q: '4. Human activities can make resources fit for use.', a: 'True' },
            { q: '5. All natural resources get replenished at the same pace.', a: 'False' },
            { q: '6. Fossil fuels can be recycled.', a: 'False' },
        ],
    },
    {
        title: 'H. Choose the Correct Option',
        questions: [
            { q: '1. Health is...', a: '(b) a human resource' },
            { q: '2. Which of the following is an inexhaustible resource?', a: '(d) sunlight' },
            { q: '3. Technology is...', a: '(c) a man-made resource' },
            { q: '4. Which of the following resources is non-renewable but can be recycled?', a: '(d) iron' },
            { q: '5. Sustainable development seeks to prevent...', a: '(d) all of these' },
        ],
    },
];
